[pytest]
# Путь к тестам
testpaths = tests

# Шаблоны для поиска тестов
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Настройки покрытия
addopts =
    --cov=src
    --cov-report=html
    --cov-report=term-missing
    --cov-fail-under=80
    -v